declare module 'lucide-react-native/dist/esm/icons/arrow-left' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/arrow-right' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/arrow-up-right' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/bookmark' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/camera' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/check' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/chevron-down' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/chevron-up' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/circle-user-round' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/crown' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/download' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/external-link' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/folder' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/folder-plus' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/image-plus' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/layers' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/locate-fixed' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/lock-keyhole' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/log-out' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/mail' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/mail-check' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/map-pin' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/ellipsis' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/move-horizontal' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/plus' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/refresh-cw' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/settings' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/share-2' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/shield-check' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/shopping-bag' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/sparkles' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/trash-2' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/wand-sparkles' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
declare module 'lucide-react-native/dist/esm/icons/x' { const Icon: import('lucide-react-native').LucideIcon; export default Icon; }
